# Print words with the terminal color console control codes
colorwithbash:
    #!/usr/bin/env bash
    declare -A COLOR_TABLE
    COLOR_TABLE=(4 blue \
                 13 pink \
                 1 red \
                 11 yellow \
                 2 green)
    NUM_ELEMENTS="${#COLOR_TABLE[*]}"
    declare -a KEY_ARRAY
    KEY_ARRAY=($(echo "${!COLOR_TABLE[*]}"))
    printf "\033[39m"
    i=1
    while (( i <= 1000 ))
    do
        NUMBER=$(("$RANDOM" % "$NUM_ELEMENTS" ))
        KEY="${KEY_ARRAY[$NUMBER]}"
        COLOR="${COLOR_TABLE[$KEY]}"
        printf "\033[38;5;%sm%s " "$KEY" "$COLOR"
        i=$((i+1))
    done
    printf "\033[39m"


# Use Nu shell to print a some color coded words, this is "the hard way"
colortime:
    #!/usr/bin/env nu

    const COLOR_TABLE = [[color code]; [blue 4] [pink 13] [ red 1 ] [yellow 11] [green 2]]

    print -n (ansi reset)
    mut x = 0

    while $x < 1000 {
        let rand_num = ( random int 0..($COLOR_TABLE | drop 1 | length))
        let color_code = ($COLOR_TABLE | select $rand_num)
        let code = $"38;5;($color_code | get code | first)m"
        let color = ($color_code | get color | first)
        print -n $"(ansi --escape ($code))($color) "
        $x = $x + 1
    }
    print (ansi reset)
